name: Fronntend Application CICD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Appllication Build CI
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: React-App-${{ github.run_id }}
          path: build/
  deploy:
    runs-on: self-hosted
    needs: build
    name: Deploy - Release
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8
        with:
          # Artifact name
          name: React-App-${{ github.run_id }}
          # github-token: ${{ GITHUB.TOKEN }}
          # Destination path
          path: ${{ runner.temp }}
          # run-id: 23523068344
          
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AZHOST }}
          username: ${{ secrets.AZUSERNAME }}
          password: ${{ secrets.AZPASSWORD }}
          port: ${{ secrets.AZPORT }}
          source: ${{ runner.temp }}/*
          target: /tmp/artifacts
          strip_components: 4
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZHOST }}
          port: ${{ secrets.AZPORT }}
          username: ${{ secrets.AZUSERNAME }}
          password: ${{ secrets.AZPASSWORD }}
          script_stop: true
          script: |
            sudo cp -r /tmp/artifacts/* /var/www/html/
            sudo systemctl restart nginx
      
