name: Frontend Application CICD
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  
  # build:
  #   runs-on: ubuntu-latest
  #   name: Application Build CI
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6.0.2
  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 16.x
  #     - name: Install Dependencies
  #       run: npm install
  #     - name: Build Application
  #       run: npm run build
  #       env:
  #         CI: false
  #     - name: Upload Build Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: React-App-${{ github.run_id }}
  #         path: build/

  deploy:
    runs-on: ubuntu-latest
    # needs: build                             
    name: Deploy - Release
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v8     
        with:
          name: React-App-23581225385          
          github-token: ${{ GITHUB.TOKEN }}   
          path: react-app
          run-id: 23581225385                  

      - name: Copy Files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AZHOST }}
          username: ${{ secrets.AZUSERNAME }}  
          password: ${{ secrets.AZPASSWORD }}  
          port: ${{ secrets.AZPORT }}
          source: react-app/*                  
          target: /var/www/html/               
          strip_components: 1                  

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZHOST }}
          port: ${{ secrets.AZPORT }}
          username: ${{ secrets.AZUSERNAME }}
          password: ${{ secrets.AZPASSWORD }}
          script_stop: true
          script: |
            sudo systemctl restart nginx
